In [51]:
import numpy as np

from sympy import isprime

g = 5
P = 30

G = sorted({pow(g, x, P) for x in range(P)})
Q = len(G)
F = sorted({x for x in range(len(G))})

print(f"The group G = <{g}>_{P} = {G} has order {Q}")
print(f"The underlying field is F = {F}")

def comp_G(x, y):
    return (x * y) % P

def comp_F(x, y):
    return (x + y) % Q

def log_G(x):
    for i in range(Q):
        if pow(g, i, P) == x:
            return i
    return 0


The group G = <5>_30 = [1, 5, 25] has order 3
The underlying field is F = [0, 1, 2]


In [52]:

post = np.array([[log_G(comp_G(x, y)) for y in G] for x in G])
pre = np.array([[comp_F(log_G(x), log_G(y)) for y in G] for x in G])
print(post)
print(pre)
print(np.all(post == pre))
for x in G:
    for y in G:
        print(f"log({x} * {y}) = {log_G(comp_G(x, y))}, log({x}) + log({y}) = {comp_F(log_G(x), log_G(y))}")


[[0 1 2]
 [1 2 1]
 [2 1 2]]
[[0 1 2]
 [1 2 0]
 [2 0 1]]
False
log(1 * 1) = 0, log(1) + log(1) = 0
log(1 * 5) = 1, log(1) + log(5) = 1
log(1 * 25) = 2, log(1) + log(25) = 2
log(5 * 1) = 1, log(5) + log(1) = 1
log(5 * 5) = 2, log(5) + log(5) = 2
log(5 * 25) = 1, log(5) + log(25) = 0
log(25 * 1) = 2, log(25) + log(1) = 2
log(25 * 5) = 1, log(25) + log(5) = 0
log(25 * 25) = 2, log(25) + log(25) = 1
